AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create a DynamoDB table for contact messages

Resources:
  ContactMessagesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ContactMessages
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

Outputs:
  TableName:
    Description: Name of the DynamoDB table
    Value: !Ref ContactMessagesTable
